name: ci

on:
    pull_request:
        types:
            - opened

    push:

jobs:
    check-commit:
        name: Check Commit

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.7

              with:
                  fetch-depth: 0

            - uses: actions/cache@v4.0.2

              with:
                  key: ${{ github.job }}-${{ hashFiles('package-lock.json') }}

                  path: node_modules/

            - uses: actions/setup-node@v4.0.2

              with:
                  node-version: 20

            - name: Install dependencies

              run: npm install

            - name: Check commit

              run: npx commitlint --from=HEAD~1 --to HEAD --verbose

    check-format:
        name: Check Format

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.7

            - uses: actions/cache@v4.0.2

              with:
                  key: ${{ github.job }}-${{ hashFiles('package-lock.json') }}

                  path: node_modules/

            - uses: actions/setup-node@v4.0.2

              with:
                  node-version: 20

            - name: Install dependencies

              run: npm install

            - name: Check format

              run: npm run prettier:check

    check-functionality:
        name: Check Functionality

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.7

            - uses: actions/cache@v4.0.2

              with:
                  key: ${{ github.job }}-${{ hashFiles('package-lock.json') }}

                  path: node_modules/

            - uses: actions/setup-node@v4.0.2

              with:
                  node-version: 20

            - name: Install dependencies

              run: npm install

            - name: Check functionality

              run: npm test

            - if: ${{ !cancelled() }}

              uses: actions/upload-artifact@v4.3.4

              with:
                  name: act.log

                  path: ./act.log

    check-style:
        name: Check Style

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.1.7

            - uses: actions/cache@v4.0.2

              with:
                  key: ${{ github.job }}-${{ hashFiles('package-lock.json') }}

                  path: node_modules/

            - uses: actions/setup-node@v4.0.2

              with:
                  node-version: 20

            - name: Install dependencies

              run: npm install

            - name: Check style

              run: npm run eslint:check

    release-please:
        if: ${{ github.ref == 'refs/heads/main' }}

        name: Release Please

        needs:
            - check-commit
            - check-format
            - check-functionality
            - check-style

        permissions:
            contents: write

            pull-requests: write

        runs-on: ubuntu-latest

        steps:
            - uses: google-github-actions/release-please-action@v4.1.1

              with:
                  release-type: node
